// Guest task supervisor for agent-fleet workers (see docs/agent-fleet.md and
// agent-vm.mod.nix). Runs as guest root inside a disposable, network-contained
// microVM: waits for the host drainer to deliver a task into the virtiofs
// exchange, validates the host-staged canonical metadata and the exactly-one
// selected credential, prepares the cockpit-built context capsule as the
// selected unprivileged executor, runs the provider executor (or the fixed
// deterministic verifier), captures the workspace patch, distills a
// root-produced usage record, and publishes the exit code LAST.
//
// Trust model: guest root is orchestration authority; executors and verifier
// checks are unprivileged users. Everything on the task share and inside the
// context capsule is hostile — no symlink following, bounded reads, no shell
// interpolation. Fixed external tools (runuser, tar, git, jq, sqlite3, cp,
// chown, pkill) do the extraction/execution legwork; all orchestration,
// validation, lifecycle, and publication decisions live here.

use std::collections::BTreeMap;
use std::fs::{self, File, OpenOptions};
use std::io::{Read, Write};
use std::os::unix::fs::{MetadataExt, OpenOptionsExt, PermissionsExt};
use std::os::unix::process::ExitStatusExt;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::mpsc;
use std::thread;
use std::time::{Duration, SystemTime};
use std::{env, io};

type Result<T> = std::result::Result<T, String>;

// asm-generic values, identical on x86_64 and aarch64 Linux.
const O_NOFOLLOW: i32 = 0o400000;
const O_CLOEXEC: i32 = 0o2000000;
const O_NONBLOCK: i32 = 0o4000;

// The host publishes prompt.md at <=1 MiB and task-meta at a few lines; these
// guest-side caps only ever reject inputs the host protocol can not produce.
const PROMPT_MAX_BYTES: u64 = 8 * 1024 * 1024;
const META_MAX_BYTES: u64 = 4096;
const CREDENTIAL_MAX_BYTES: u64 = 1024 * 1024;
const HINT_MAX_BYTES: u64 = 1024 * 1024;
const USAGE_MAX_BYTES: u64 = 64 * 1024 * 1024;
const USAGE_MAX_FILES: usize = 4096;
const USAGE_MAX_DEPTH: usize = 64;
const COMMAND_OUTPUT_MAX_BYTES: usize = 8 * 1024 * 1024;

#[derive(Clone, Debug)]
struct Config {
    task_dir: PathBuf,
    creds_dir: PathBuf,
    workspace: PathBuf,
    context_root: PathBuf,
    hint_file: PathBuf,
    exec_claude: PathBuf,
    exec_codex: PathBuf,
    exec_opencode: PathBuf,
    exec_local: PathBuf,
}

impl Config {
    fn from_env() -> Result<Self> {
        Ok(Self {
            task_dir: env_path_or("FLEET_GUEST_TASK_DIR", "/run/task"),
            creds_dir: env_path_or("FLEET_GUEST_CREDS_DIR", "/run/host-creds"),
            workspace: env_path_or("FLEET_GUEST_WORKSPACE", "/workspace"),
            context_root: env_path_or("FLEET_GUEST_CONTEXT_ROOT", "/run/fleet-context"),
            hint_file: env_path("FLEET_GUEST_HINT_FILE")?,
            exec_claude: env_path("FLEET_GUEST_EXEC_CLAUDE")?,
            exec_codex: env_path("FLEET_GUEST_EXEC_CODEX")?,
            exec_opencode: env_path("FLEET_GUEST_EXEC_OPENCODE")?,
            exec_local: env_path("FLEET_GUEST_EXEC_LOCAL")?,
        })
    }

    fn task(&self, name: &str) -> PathBuf {
        self.task_dir.join(name)
    }
}

// Canonical task metadata, generated by the host dispatcher into the
// read-only credential share. The guest never reparses executor fields from
// the prompt.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
struct TaskMeta {
    agent: String,
    model: String,
    effort: String,
}

fn parse_task_meta(text: &str) -> Result<TaskMeta> {
    let mut fields = BTreeMap::new();
    for line in text.lines() {
        if line.is_empty() {
            continue;
        }
        let (key, value) = line
            .split_once('=')
            .ok_or_else(|| format!("malformed task-meta line: {line}"))?;
        if !matches!(key, "agent" | "model" | "effort") {
            return Err(format!("unexpected task-meta key: {key}"));
        }
        if !valid_token(value) {
            return Err(format!("invalid task-meta value for {key}"));
        }
        if fields.insert(key.to_string(), value.to_string()).is_some() {
            return Err(format!("duplicate task-meta key: {key}"));
        }
    }
    let field = |name: &str| fields.get(name).cloned().unwrap_or_default();
    Ok(TaskMeta {
        agent: field("agent"),
        model: field("model"),
        effort: field("effort"),
    })
}

fn valid_token(value: &str) -> bool {
    value.len() <= 64
        && value
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || "._/-".contains(character))
}

// The executor identity selected by agent/model. Users and homes are the
// static guest accounts from agent-vm.mod.nix.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum ExecutorKind {
    Claude,
    Codex,
    Opencode,
    Local,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct Executor {
    kind: ExecutorKind,
    user: &'static str,
    home: &'static str,
}

fn select_executor(agent: &str, model: &str) -> Option<Executor> {
    let executor = |kind, user, home| Some(Executor { kind, user, home });
    match agent {
        "claude" => executor(ExecutorKind::Claude, "agent-claude", "/home/agent-claude"),
        "codex" => executor(ExecutorKind::Codex, "agent-codex", "/home/agent-codex"),
        "opencode" if model.starts_with("local/") => {
            executor(ExecutorKind::Local, "agent-local", "/home/agent-local")
        }
        "opencode" if model.starts_with("openrouter/") => executor(
            ExecutorKind::Opencode,
            "agent-opencode",
            "/home/agent-opencode",
        ),
        _ => None,
    }
}

// Exact credential expectation for an agent/model pair. The host stages
// exactly the selected executor's credential; anything else is a rejection.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum CredentialRule {
    Exactly(&'static str),
    None,
    Invalid,
}

fn credential_rule(agent: &str, model: &str) -> CredentialRule {
    match (agent, model) {
        ("claude", _) => CredentialRule::Exactly("claude-token"),
        ("codex", _) => CredentialRule::Exactly("codex-auth.json"),
        ("opencode", model) if model.starts_with("openrouter/") => {
            CredentialRule::Exactly("openrouter-key")
        }
        ("opencode", model) if model.starts_with("local/") => CredentialRule::None,
        _ => CredentialRule::Invalid,
    }
}

// One entry in the credential share (task-meta excluded). `regular` is true
// only for a regular, non-symlink file.
#[derive(Clone, Debug)]
struct CredentialEntry {
    name: String,
    regular: bool,
}

fn credentials_match(entries: &[CredentialEntry], rule: CredentialRule) -> bool {
    if entries.iter().any(|entry| !entry.regular) {
        return false;
    }
    match rule {
        CredentialRule::Exactly(name) => entries.len() == 1 && entries[0].name == name,
        CredentialRule::None => entries.is_empty(),
        CredentialRule::Invalid => false,
    }
}

// Strip a leading front-matter block exactly like the previous awk program:
// only a "---" on the very first line opens a header, everything up to the
// closing "---" is dropped, and an unterminated header swallows the whole
// prompt.
fn strip_front_matter(prompt: &str) -> String {
    let mut lines = prompt.lines();
    let mut body = String::new();
    let mut push = |line: &str| {
        body.push_str(line);
        body.push('\n');
    };
    match lines.next() {
        None => return body,
        Some("---") => {
            for line in lines.by_ref() {
                if line == "---" {
                    break;
                }
            }
        }
        Some(first) => push(first),
    }
    lines.for_each(push);
    body
}

// $(cat file) semantics: command substitution strips all trailing newlines.
fn trim_trailing_newlines(value: &str) -> &str {
    value.trim_end_matches('\n')
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

// The final publication sequence. Order is security-relevant: the exchange
// must be locked (root:root 0750) and the executor's processes killed before
// the root-produced .trusted/usage.json exists, and exit-code — the host's
// completion signal — must be the very last artifact.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum FinalStep {
    CapturePatch,
    LockExchange,
    KillExecutor,
    ResetTrusted,
    PublishUsage,
    PublishExitCode,
}

fn final_steps(has_user: bool, has_baseline: bool, git_present: bool) -> Vec<FinalStep> {
    let mut steps = Vec::new();
    if has_user && has_baseline && git_present {
        steps.push(FinalStep::CapturePatch);
    }
    steps.push(FinalStep::LockExchange);
    if has_user {
        steps.push(FinalStep::KillExecutor);
    }
    steps.push(FinalStep::ResetTrusted);
    if has_user {
        steps.push(FinalStep::PublishUsage);
    }
    steps.push(FinalStep::PublishExitCode);
    steps
}

// Task outcome and its published exit code. 64/65/66 match the previous
// supervisor and the host dispatcher's expectations.
#[derive(Clone, Debug, Eq, PartialEq)]
enum Outcome {
    CredentialRejected,
    ContextFailed(String),
    MetaRejected,
    InternalFailed(String),
    Ran(i32),
}

impl Outcome {
    fn exit_code(&self) -> i32 {
        match self {
            Self::CredentialRejected => 66,
            Self::ContextFailed(_) => 65,
            Self::MetaRejected => 64,
            Self::InternalFailed(_) => 70,
            Self::Ran(code) => *code,
        }
    }

    // Report/log text for pre-execution outcomes; executed tasks produce
    // their own report and log.
    fn message(&self) -> Option<String> {
        match self {
            Self::CredentialRejected => {
                Some("task rejected: credential set does not match selected executor\n".into())
            }
            Self::ContextFailed(log) => Some(format!(
                "task failed: context capsule could not be prepared\n{log}"
            )),
            Self::MetaRejected => {
                Some("task rejected: agent and model must both be specified\n".into())
            }
            Self::InternalFailed(error) => {
                Some(format!("task failed: guest supervisor error\n{error}\n"))
            }
            Self::Ran(_) => None,
        }
    }
}

// ---------------------------------------------------------------------------
// Filesystem helpers: symlink-refusing, bounded.

fn open_nofollow(path: &Path) -> io::Result<File> {
    OpenOptions::new()
        .read(true)
        .custom_flags(O_NOFOLLOW | O_CLOEXEC)
        .open(path)
}

fn is_regular_nofollow(path: &Path) -> bool {
    fs::symlink_metadata(path)
        .map(|metadata| metadata.file_type().is_file())
        .unwrap_or(false)
}

fn read_bounded(path: &Path, limit: u64) -> Result<String> {
    let file = open_nofollow(path).map_err(|error| format!("open {}: {error}", path.display()))?;
    let metadata = file
        .metadata()
        .map_err(|error| format!("inspect {}: {error}", path.display()))?;
    if !metadata.file_type().is_file() || metadata.len() > limit {
        return Err(format!("unsafe or oversized file: {}", path.display()));
    }
    let mut text = String::new();
    file.take(limit.saturating_add(1))
        .read_to_string(&mut text)
        .map_err(|error| format!("read {}: {error}", path.display()))?;
    if text.len() as u64 > limit {
        return Err(format!("file grew beyond bound: {}", path.display()));
    }
    Ok(text)
}

fn touch(path: &Path) -> Result<()> {
    let file = OpenOptions::new()
        .create(true)
        .truncate(false)
        .write(true)
        .custom_flags(O_NOFOLLOW | O_CLOEXEC | O_NONBLOCK)
        .open(path)
        .map_err(|error| format!("touch {}: {error}", path.display()))?;
    if !file
        .metadata()
        .map_err(|error| format!("inspect {}: {error}", path.display()))?
        .file_type()
        .is_file()
    {
        return Err(format!(
            "refusing to touch non-regular file: {}",
            path.display()
        ));
    }
    file.set_modified(SystemTime::now())
        .map_err(|error| format!("touch {}: {error}", path.display()))
}

fn set_mode(path: &Path, mode: u32) -> Result<()> {
    fs::set_permissions(path, fs::Permissions::from_mode(mode))
        .map_err(|error| format!("chmod {:04o} {}: {error}", mode, path.display()))
}

// Ownership by account name goes through chown(1) so the supervisor never
// hand-parses the user database.
fn chown_name(path: &Path, owner: &str) -> Result<()> {
    let status = Command::new("chown")
        .arg(owner)
        .arg(path)
        .status()
        .map_err(|error| format!("run chown for {}: {error}", path.display()))?;
    if !status.success() {
        return Err(format!("chown {owner} {} failed", path.display()));
    }
    Ok(())
}

fn ensure_dir(path: &Path, mode: u32, owner: Option<&str>) -> Result<()> {
    fs::create_dir_all(path).map_err(|error| format!("mkdir {}: {error}", path.display()))?;
    set_mode(path, mode)?;
    if let Some(owner) = owner {
        chown_name(path, owner)?;
    }
    Ok(())
}

fn write_new(path: &Path, contents: &[u8], mode: u32) -> Result<()> {
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(mode)
        .custom_flags(O_NOFOLLOW | O_CLOEXEC)
        .open(path)
        .map_err(|error| format!("create {}: {error}", path.display()))?;
    file.write_all(contents)
        .and_then(|()| file.sync_all())
        .map_err(|error| format!("write {}: {error}", path.display()))
}

fn create_new(path: &Path, mode: u32) -> Result<File> {
    OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(mode)
        .custom_flags(O_NOFOLLOW | O_CLOEXEC | O_NONBLOCK)
        .open(path)
        .map_err(|error| format!("create {}: {error}", path.display()))
}

fn remove_any(path: &Path) -> Result<()> {
    match fs::symlink_metadata(path) {
        Err(_) => Ok(()),
        Ok(metadata) if metadata.file_type().is_dir() => {
            fs::remove_dir_all(path).map_err(|error| format!("remove {}: {error}", path.display()))
        }
        Ok(_) => {
            fs::remove_file(path).map_err(|error| format!("remove {}: {error}", path.display()))
        }
    }
}

fn write_replace(path: &Path, contents: &[u8], mode: u32) -> Result<()> {
    remove_any(path)?;
    write_new(path, contents, mode)
}

// Sorted regular (non-symlink) files in one directory whose name matches.
fn matching_files(directory: &Path, matches: impl Fn(&str) -> bool) -> Vec<PathBuf> {
    let Ok(entries) = fs::read_dir(directory) else {
        return Vec::new();
    };
    let mut paths: Vec<PathBuf> = entries
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| {
            path.file_name()
                .and_then(|name| name.to_str())
                .is_some_and(&matches)
                && is_regular_nofollow(path)
        })
        .collect();
    paths.sort();
    paths
}

// Recursive walk collecting regular *.suffix files; never follows symlinks.
fn walk_files(directory: &Path, suffix: &str, into: &mut Vec<PathBuf>, depth: usize) {
    if depth >= USAGE_MAX_DEPTH || into.len() >= USAGE_MAX_FILES {
        return;
    }
    let Ok(entries) = fs::read_dir(directory) else {
        return;
    };
    let mut paths: Vec<PathBuf> = entries.flatten().map(|entry| entry.path()).collect();
    paths.sort();
    for path in paths {
        let Ok(metadata) = fs::symlink_metadata(&path) else {
            continue;
        };
        if metadata.file_type().is_dir() {
            walk_files(&path, suffix, into, depth + 1);
        } else if metadata.file_type().is_file()
            && path
                .file_name()
                .and_then(|name| name.to_str())
                .is_some_and(|name| name.ends_with(suffix))
        {
            into.push(path);
            if into.len() >= USAGE_MAX_FILES {
                return;
            }
        }
    }
}

// ---------------------------------------------------------------------------
// External command helpers.

// The exact invocation shape the Bash supervisor used for unprivileged work:
// runuser -u <user> -- env HOME=<home> <program> <args...>.
fn runuser_command(user: &str, home: &str) -> Command {
    let mut command = Command::new("runuser");
    command.args(["-u", user, "--", "env"]);
    command.arg(format!("HOME={home}"));
    command
}

struct BoundedOutput {
    status: std::process::ExitStatus,
    stdout: Vec<u8>,
    stderr: Vec<u8>,
}

fn drain_bounded(mut reader: impl Read, limit: usize) -> Vec<u8> {
    let mut kept = Vec::new();
    let mut buffer = [0_u8; 8192];
    while let Ok(read) = reader.read(&mut buffer) {
        if read == 0 {
            break;
        }
        let remaining = limit.saturating_sub(kept.len());
        kept.extend_from_slice(&buffer[..read.min(remaining)]);
    }
    kept
}

fn command_output_bounded(command: &mut Command, limit: usize) -> Result<BoundedOutput> {
    command.stdout(Stdio::piped()).stderr(Stdio::piped());
    let mut child = command
        .spawn()
        .map_err(|error| format!("run {command:?}: {error}"))?;
    let stdout = child
        .stdout
        .take()
        .ok_or_else(|| "command stdout pipe is missing".to_string())?;
    let stderr = child
        .stderr
        .take()
        .ok_or_else(|| "command stderr pipe is missing".to_string())?;
    let stdout_reader = thread::spawn(move || drain_bounded(stdout, limit));
    let stderr_reader = thread::spawn(move || drain_bounded(stderr, limit));
    let status = child
        .wait()
        .map_err(|error| format!("wait for {command:?}: {error}"))?;
    let stdout = stdout_reader
        .join()
        .map_err(|_| "command stdout reader panicked".to_string())?;
    let stderr = stderr_reader
        .join()
        .map_err(|_| "command stderr reader panicked".to_string())?;
    Ok(BoundedOutput {
        status,
        stdout,
        stderr,
    })
}

fn append_bounded(log: &mut String, bytes: &[u8]) {
    let remaining = COMMAND_OUTPUT_MAX_BYTES.saturating_sub(log.len());
    if remaining > 0 {
        log.push_str(&String::from_utf8_lossy(
            &bytes[..bytes.len().min(remaining)],
        ));
    }
}

// Run a command, appending stdout+stderr to a preparation log; Err on
// nonzero exit so context preparation aborts like `|| return` did.
fn run_logged(command: &mut Command, log: &mut String) -> Result<()> {
    let output = command_output_bounded(command, COMMAND_OUTPUT_MAX_BYTES)?;
    append_bounded(log, &output.stdout);
    append_bounded(log, &output.stderr);
    if !output.status.success() {
        return Err(format!("{command:?} exited {}", output.status));
    }
    Ok(())
}

fn run_captured(command: &mut Command, log: &mut String) -> Result<String> {
    let output = command_output_bounded(command, COMMAND_OUTPUT_MAX_BYTES)?;
    append_bounded(log, &output.stderr);
    if !output.status.success() {
        append_bounded(log, &output.stdout);
        return Err(format!("{command:?} exited {}", output.status));
    }
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

fn exit_code_of(status: std::process::ExitStatus) -> i32 {
    status
        .code()
        .or_else(|| status.signal().map(|signal| 128 + signal))
        .unwrap_or(1)
}

// Pipe text through a fixed jq program; best-effort — None on any failure
// or empty output, exactly like the previous `... | jq ... || usage=""`.
fn tool_command(executor: Option<&Executor>, program: &str) -> Command {
    if let Some(executor) = executor {
        let mut command = runuser_command(executor.user, executor.home);
        command.arg(program);
        command
    } else {
        Command::new(program)
    }
}

fn jq_filter(args: &[&str], stdin_text: &str, executor: Option<&Executor>) -> Option<String> {
    let mut child = tool_command(executor, "jq")
        .args(args)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;
    // A jq that stops reading must not deadlock the writer: feed stdin from
    // a thread while draining stdout here.
    let mut stdin = child.stdin.take()?;
    let text = stdin_text.to_string();
    let writer = thread::spawn(move || {
        let _ = stdin.write_all(text.as_bytes());
    });
    let output = child.wait_with_output().ok()?;
    let _ = writer.join();
    let result = String::from_utf8_lossy(&output.stdout)
        .trim_end()
        .to_string();
    (output.status.success() && !result.is_empty()).then_some(result)
}

fn concatenate_files(paths: &[PathBuf]) -> String {
    let mut text = String::new();
    for path in paths {
        let remaining = USAGE_MAX_BYTES.saturating_sub(text.len() as u64);
        if remaining == 0 {
            break;
        }
        if let Ok(file) = open_nofollow(path) {
            let _ = file.take(remaining).read_to_string(&mut text);
        }
    }
    text
}

// ---------------------------------------------------------------------------
// Trusted usage extraction. Root distills the executor's own usage records
// (Claude/codex: JSONL transcripts; opencode: SQLite) into one normalized
// record. Strictly best-effort: a missing or unparsable store must never
// fail the task. Field names: input/output are totals (output includes
// reasoning); cache_read and cache_creation follow Anthropic's split, and
// codex's cached_input maps to cache_read.

const CLAUDE_USAGE_FILTER: &str = r#"
  [ .[] | select(.type=="assistant" and .message.usage != null)
    | {id: ((.requestId//"") + "/" + (.message.id//"")), u: .message.usage, m: .message.model} ]
  | unique_by(.id)
  | select(length > 0)
  | { executor: "claude",
      model: ((map(.m) | map(select(. != null)) | last) // "unknown"),
      input_tokens: (map(.u.input_tokens//0) | add),
      output_tokens: (map(.u.output_tokens//0) | add),
      cache_read_tokens: (map(.u.cache_read_input_tokens//0) | add),
      cache_creation_tokens: (map(.u.cache_creation_input_tokens//0) | add) }"#;

const CODEX_SESSION_FILTER: &str = r#"
  { m: ([ .[] | select(.type=="turn_context") | .payload.model ] | last),
    t: ([ .[] | select(.type=="event_msg" and .payload.type=="token_count"
                and .payload.info.total_token_usage != null)
          | .payload.info.total_token_usage ] | last) }
  | select(.t != null)"#;

// OpenAI input_tokens INCLUDES cached; normalize to the Anthropic
// convention (input = uncached).
const CODEX_COMBINE_FILTER: &str = r#"
  select(length > 0)
  | { executor: "codex",
      model: ((map(.m) | map(select(. != null)) | last) // "unknown"),
      input_tokens: ((map(.t.input_tokens//0) | add) - (map(.t.cached_input_tokens//0) | add)),
      output_tokens: (map(.t.output_tokens//0) | add),
      cache_read_tokens: (map(.t.cached_input_tokens//0) | add),
      cache_creation_tokens: 0 }"#;

const OPENCODE_USAGE_FILTER: &str = r#"
  [ .[] | .data | fromjson | select(.role=="assistant" and .tokens != null) ]
  | select(length > 0)
  | { executor: "opencode",
      model: (((map(.providerID) | map(select(. != null)) | last) // "?") + "/"
              + ((map(.modelID) | map(select(. != null)) | last) // "unknown")),
      input_tokens: (map(.tokens.input//0) | add),
      output_tokens: ((map(.tokens.output//0) | add) + (map(.tokens.reasoning//0) | add)),
      cache_read_tokens: (map(.tokens.cache.read//0) | add),
      cache_creation_tokens: (map(.tokens.cache.write//0) | add) }"#;

fn claude_usage(home: &Path, executor: Option<&Executor>) -> Option<String> {
    let mut transcripts = Vec::new();
    walk_files(
        &home.join(".claude/projects"),
        ".jsonl",
        &mut transcripts,
        0,
    );
    jq_filter(
        &["-cs", CLAUDE_USAGE_FILTER],
        &concatenate_files(&transcripts),
        executor,
    )
}

// total_token_usage is cumulative per session file: take each file's final
// value, then sum the files.
fn codex_usage(home: &Path, executor: Option<&Executor>) -> Option<String> {
    let mut sessions = Vec::new();
    walk_files(&home.join(".codex/sessions"), ".jsonl", &mut sessions, 0);
    let mut finals = String::new();
    let mut input_budget = USAGE_MAX_BYTES;
    for session in &sessions {
        if input_budget == 0 {
            break;
        }
        if let Ok(file) = open_nofollow(session) {
            let mut text = String::new();
            if file.take(input_budget).read_to_string(&mut text).is_ok()
                && let Some(value) = jq_filter(&["-cs", CODEX_SESSION_FILTER], &text, executor)
            {
                finals.push_str(&value);
                finals.push('\n');
            }
            input_budget = input_budget.saturating_sub(text.len() as u64);
        }
    }
    jq_filter(&["-cs", CODEX_COMBINE_FILTER], &finals, executor)
}

fn opencode_usage(home: &Path, executor: Option<&Executor>) -> Option<String> {
    let store = home.join(".local/share/opencode");
    let database = matching_files(&store, |name| name.ends_with(".db"))
        .into_iter()
        .next()?;
    let metadata = open_nofollow(&database).ok()?.metadata().ok()?;
    if !metadata.file_type().is_file() || metadata.len() > USAGE_MAX_BYTES {
        return None;
    }
    let rows = command_output_bounded(
        tool_command(executor, "sqlite3")
            .args(["-readonly", "-json"])
            .arg(&database)
            .arg("select data from message")
            .stdin(Stdio::null()),
        USAGE_MAX_BYTES as usize,
    )
    .ok()?;
    if !rows.status.success() {
        return None;
    }
    jq_filter(
        &["-c", OPENCODE_USAGE_FILTER],
        &String::from_utf8_lossy(&rows.stdout),
        executor,
    )
}

fn extract_usage(executor: &Executor) -> Option<String> {
    let home = Path::new(executor.home);
    match executor.kind {
        ExecutorKind::Claude => claude_usage(home, Some(executor)),
        ExecutorKind::Codex => codex_usage(home, Some(executor)),
        ExecutorKind::Opencode | ExecutorKind::Local => opencode_usage(home, Some(executor)),
    }
}

// ---------------------------------------------------------------------------
// Context preparation. The capsule is an opaque cockpit-built archive,
// extracted only here, as the selected unprivileged user.

#[derive(Clone, Debug, Default)]
struct ContextInfo {
    baseline: String,
}

struct Supervisor {
    config: Config,
}

impl Supervisor {
    fn prepare_context(&self, executor: &Executor, log: &mut String) -> Result<ContextInfo> {
        let config = &self.config;
        let user = executor.user;
        let owner = format!("{user}:users");
        // The volume mount can supersede tmpfiles-created metadata; repair
        // the shared workspace mode after mounts are live.
        ensure_dir(&config.workspace, 0o770, Some(&owner))?;
        ensure_dir(&config.context_root, 0o700, Some(&owner))?;
        run_logged(
            runuser_command(user, executor.home)
                .args(["tar", "--extract", "--zstd"])
                .args([
                    "--no-same-owner",
                    "--no-same-permissions",
                    "--no-overwrite-dir",
                ])
                .arg("--directory")
                .arg(&config.context_root)
                .arg("--file")
                .arg(config.task("context.tar.zst")),
            log,
        )?;

        let mut info = ContextInfo::default();
        let mut source = config.context_root.as_os_str().to_os_string();
        source.push("/.");
        run_logged(
            runuser_command(user, executor.home)
                .args(["cp", "-a"])
                .arg(source)
                .arg(&config.workspace),
            log,
        )?;

        let git = |args: &[&str]| {
            let mut command = runuser_command(user, executor.home);
            command
                .arg("git")
                .arg("-C")
                .arg(&config.workspace)
                .args(args);
            command
        };
        run_logged(&mut git(&["init", "--quiet"]), log)?;
        run_logged(&mut git(&["config", "user.name", user]), log)?;
        run_logged(
            &mut git(&["config", "user.email", &format!("{user}@agents.invalid")]),
            log,
        )?;
        run_logged(&mut git(&["add", "-A"]), log)?;
        run_logged(
            &mut git(&[
                "commit",
                "--quiet",
                "--allow-empty",
                "-m",
                "fleet context baseline",
            ]),
            log,
        )?;
        info.baseline = run_captured(&mut git(&["rev-parse", "HEAD"]), log)?
            .trim_end()
            .to_string();
        Ok(info)
    }

    // -----------------------------------------------------------------------
    // Credential installation: exactly the selected executor's credential,
    // into that executor's private location, 0400, nothing broader.

    fn credential_entries(&self) -> Vec<CredentialEntry> {
        let Ok(entries) = fs::read_dir(&self.config.creds_dir) else {
            return Vec::new();
        };
        let mut found: Vec<CredentialEntry> = entries
            .flatten()
            .filter(|entry| entry.file_name() != "task-meta")
            .map(|entry| CredentialEntry {
                name: entry.file_name().to_string_lossy().into_owned(),
                regular: is_regular_nofollow(&entry.path()),
            })
            .collect();
        found.sort_by(|left, right| left.name.cmp(&right.name));
        found
    }

    // One credential file into the executor's private location: 0700 dir,
    // 0400 file, owned by that executor, nothing broader.
    fn install_secret(&self, directory: &Path, file: &str, owner: &str, contents: &[u8]) -> Result<()> {
        ensure_dir(directory, 0o700, Some(owner))?;
        let destination = directory.join(file);
        write_replace(&destination, contents, 0o400)?;
        chown_name(&destination, owner)
    }

    fn install_credential(&self, rule: CredentialRule) -> Result<()> {
        let CredentialRule::Exactly(name) = rule else {
            return Ok(());
        };
        let secret = read_bounded(&self.config.creds_dir.join(name), CREDENTIAL_MAX_BYTES)?;
        let env_line = |variable: &str| {
            format!(
                "export {variable}={}\n",
                shell_quote(trim_trailing_newlines(&secret))
            )
        };
        match name {
            "claude-token" => self.install_secret(
                Path::new("/run/agent-claude"),
                "env",
                "agent-claude:users",
                env_line("CLAUDE_CODE_OAUTH_TOKEN").as_bytes(),
            ),
            "codex-auth.json" => self.install_secret(
                Path::new("/home/agent-codex/.codex"),
                "auth.json",
                "agent-codex:users",
                secret.as_bytes(),
            ),
            "openrouter-key" => self.install_secret(
                Path::new("/run/agent-opencode"),
                "env",
                "agent-opencode:users",
                env_line("OPENROUTER_API_KEY").as_bytes(),
            ),
            other => Err(format!("unknown credential name: {other}")),
        }
    }

    // -----------------------------------------------------------------------
    // Provider execution. The VM is the sandbox: everything auto-approved.

    fn execute(&self, executor: &Executor, meta: &TaskMeta, body: &str, hint: &str) -> Result<i32> {
        let config = &self.config;
        let body = trim_trailing_newlines(body);
        let hint = trim_trailing_newlines(hint);
        let combined = format!("{hint}\n\n{body}");
        let report = || {
            let path = config.task("report.md");
            remove_any(&path)?;
            create_new(&path, 0o644)
        };
        let log = || {
            let path = config.task("agent.log");
            remove_any(&path)?;
            create_new(&path, 0o644)
        };
        let status = match executor.kind {
            ExecutorKind::Claude => {
                let mut command = runuser_command(executor.user, executor.home);
                command.arg(&config.exec_claude);
                command.args(["-p", body, "--model", &meta.model]);
                if !meta.effort.is_empty() {
                    command.args(["--effort", &meta.effort]);
                }
                command.arg("--dangerously-skip-permissions");
                command.args(["--append-system-prompt", hint]);
                command
                    .stdin(Stdio::null())
                    .stdout(report()?)
                    .stderr(log()?)
                    .status()
            }
            ExecutorKind::Codex => {
                // No system-prompt flag; the hint rides atop the prompt.
                // stdout is the session transcript (-> agent.log); the final
                // message is the report, written by the executor itself.
                let mut command = runuser_command(executor.user, executor.home);
                command.arg(&config.exec_codex);
                command.args([
                    "exec",
                    "--dangerously-bypass-approvals-and-sandbox",
                    "--skip-git-repo-check",
                    "--model",
                    &meta.model,
                ]);
                if !meta.effort.is_empty() {
                    command
                        .arg("-c")
                        .arg(format!("model_reasoning_effort={}", meta.effort));
                }
                command.arg("--output-last-message");
                command.arg(config.task("report.md"));
                command.arg(&combined);
                let transcript = log()?;
                let errors = transcript
                    .try_clone()
                    .map_err(|error| format!("clone agent.log handle: {error}"))?;
                command
                    .stdin(Stdio::null())
                    .stdout(transcript)
                    .stderr(errors)
                    .status()
            }
            ExecutorKind::Opencode | ExecutorKind::Local => {
                // stdout is the final response (-> report.md); --print-logs
                // puts the session log on stderr (-> agent.log). effort maps
                // to --variant (provider-specific reasoning effort).
                let executable = if executor.kind == ExecutorKind::Local {
                    &config.exec_local
                } else {
                    &config.exec_opencode
                };
                let mut command = runuser_command(executor.user, executor.home);
                command.arg(executable);
                command.args(["run", "--auto", "--print-logs", "--model", &meta.model]);
                if !meta.effort.is_empty() {
                    command.args(["--variant", &meta.effort]);
                }
                command.arg(&combined);
                command
                    .stdin(Stdio::null())
                    .stdout(report()?)
                    .stderr(log()?)
                    .status()
            }
        };
        status
            .map(exit_code_of)
            .map_err(|error| format!("run executor: {error}"))
    }

    // -----------------------------------------------------------------------
    // Final publication.

    fn lock_exchange(&self) -> Result<()> {
        // The supervisor always runs as guest root in production; the uid
        // check only lets the mode half of the lockdown be exercised by
        // unprivileged tests (chown to root is meaningless without root).
        if running_as_root() {
            std::os::unix::fs::chown(&self.config.task_dir, Some(0), Some(0))
                .map_err(|error| format!("chown task exchange: {error}"))?;
        }
        set_mode(&self.config.task_dir, 0o750)
    }

    fn capture_patch(&self, executor: &Executor, baseline: &str) {
        // Best-effort, as the unprivileged user, before the exchange locks.
        let _ = runuser_command(executor.user, executor.home)
            .args(["git", "-C"])
            .arg(&self.config.workspace)
            .args(["add", "--intent-to-add", "--all"])
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
        let temporary = self.config.task(".changes.patch.tmp");
        // The executor can create names in the exchange until lockdown. Remove
        // any planted entry, then use create_new+O_NOFOLLOW so a replacement
        // race can only suppress the patch, never redirect a root write.
        let _ = remove_any(&temporary);
        let produced = create_new(&temporary, 0o600).ok().and_then(|output| {
            runuser_command(executor.user, executor.home)
                .args(["git", "-C"])
                .arg(&self.config.workspace)
                .args(["diff", "--binary", "--no-ext-diff", baseline])
                .stdout(output)
                .stderr(Stdio::null())
                .status()
                .ok()
        });
        if produced.is_some_and(|status| status.success()) {
            let _ = fs::rename(&temporary, self.config.task("changes.patch"));
        } else {
            let _ = fs::remove_file(&temporary);
        }
    }

    fn publish_final<F: FnOnce()>(
        &self,
        outcome: &Outcome,
        executor: Option<&Executor>,
        context: &ContextInfo,
        before_exit_code: F,
    ) -> Result<()> {
        let git_present = self.config.workspace.join(".git").is_dir();
        let steps = final_steps(executor.is_some(), !context.baseline.is_empty(), git_present);
        let mut trusted_ready = false;
        let mut before_exit_code = Some(before_exit_code);
        for step in steps {
            match step {
                FinalStep::CapturePatch => {
                    if let Some(executor) = executor {
                        self.capture_patch(executor, &context.baseline);
                    }
                }
                FinalStep::LockExchange => self.lock_exchange()?,
                FinalStep::KillExecutor => {
                    if let Some(executor) = executor {
                        // pkill exits 1 when no process remains, which is
                        // also the desired state.
                        let _ = Command::new("pkill")
                            .args(["-KILL", "-u", executor.user])
                            .status();
                    }
                }
                FinalStep::ResetTrusted => {
                    let trusted = self.config.task(".trusted");
                    match remove_any(&trusted).and_then(|()| ensure_dir(&trusted, 0o700, None)) {
                        Ok(()) => trusted_ready = true,
                        Err(error) => {
                            eprintln!("could not reset trusted output directory: {error}")
                        }
                    }
                }
                FinalStep::PublishUsage => {
                    if trusted_ready
                        && let Some(executor) = executor
                        && let Some(usage) = extract_usage(executor)
                    {
                        let _ = write_replace(
                            &self.config.task(".trusted/usage.json"),
                            format!("{usage}\n").as_bytes(),
                            0o600,
                        );
                    }
                }
                FinalStep::PublishExitCode => {
                    if let Some(stop) = before_exit_code.take() {
                        stop();
                    }
                    write_replace(
                        &self.config.task("exit-code"),
                        format!("{}\n", outcome.exit_code()).as_bytes(),
                        0o644,
                    )?;
                }
            }
        }
        Ok(())
    }

    fn write_rejection(&self, message: &str) -> Result<()> {
        write_replace(&self.config.task("report.md"), message.as_bytes(), 0o644)?;
        write_replace(&self.config.task("agent.log"), message.as_bytes(), 0o644)
    }

    // -----------------------------------------------------------------------
    // Main task flow.

    fn run(&self) -> Result<()> {
        let config = &self.config;
        // Tell the host drainer that this guest has mounted its task share
        // and reached the delivery wait loop; refreshing it every poll is the
        // idle heartbeat the drainer requires to be FRESH before claiming.
        // Poll by READING the directory, not by statting a single
        // never-existed filename: a bare stat can sit on a stale negative
        // dentry and never see the host's delivered file.
        let prompt = config.task("prompt.md");
        loop {
            touch(&config.task(".ready"))?;
            let _ = fs::read_dir(&config.task_dir).map(|entries| entries.count());
            if is_regular_nofollow(&prompt) {
                break;
            }
            thread::sleep(Duration::from_secs(1));
        }

        // Host-generated canonical metadata lives in the read-only credential
        // share; the guest never reparses executor fields from the prompt.
        let meta_path = config.creds_dir.join("task-meta");
        let meta = if is_regular_nofollow(&meta_path) {
            read_bounded(&meta_path, META_MAX_BYTES)
                .and_then(|text| parse_task_meta(&text))
                .ok()
        } else {
            None
        };
        let (meta, mut credential_error) = match meta {
            Some(meta) => (meta, false),
            None => (TaskMeta::default(), true),
        };

        let executor = select_executor(&meta.agent, &meta.model);
        let rule = credential_rule(&meta.agent, &meta.model);
        if !credentials_match(&self.credential_entries(), rule) {
            credential_error = true;
        }
        if !credential_error
            && !meta.model.is_empty()
            && let Err(error) = self.install_credential(rule)
        {
            eprintln!("credential installation failed: {error}");
            credential_error = true;
        }

        // Heartbeat covers context preparation as well as model work, so a
        // failed/slow capsule never looks like a dead VM.
        let heartbeat_path = config.task(".heartbeat");
        let (stop_heartbeat, heartbeat_stopped) = mpsc::channel::<()>();
        let heartbeat = thread::spawn(move || {
            loop {
                let _ = touch(&heartbeat_path);
                match heartbeat_stopped.recv_timeout(Duration::from_secs(15)) {
                    Err(mpsc::RecvTimeoutError::Timeout) => {}
                    _ => break,
                }
            }
        });

        let mut context = ContextInfo::default();
        let mut context_error = None;
        if !credential_error
            && let Some(executor) = &executor
            && is_regular_nofollow(&config.task("context.tar.zst"))
        {
            let mut log = String::new();
            match self.prepare_context(executor, &mut log) {
                Ok(info) => context = info,
                Err(error) => {
                    log.push_str(&error);
                    log.push('\n');
                    context_error = Some(log);
                }
            }
        }

        let outcome = if credential_error {
            Outcome::CredentialRejected
        } else if let Some(log) = context_error {
            Outcome::ContextFailed(log)
        } else if let Some(executor) = executor.as_ref().filter(|_| !meta.model.is_empty()) {
            let execution = read_bounded(&prompt, PROMPT_MAX_BYTES).and_then(|prompt_text| {
                let body = strip_front_matter(&prompt_text);
                let hint = read_bounded(&config.hint_file, HINT_MAX_BYTES)?;
                self.execute(executor, &meta, &body, &hint)
            });
            match execution {
                Ok(code) => Outcome::Ran(code),
                Err(error) => Outcome::InternalFailed(error),
            }
        } else {
            Outcome::MetaRejected
        };
        if let Some(message) = outcome.message()
            && let Err(error) = self.write_rejection(&message)
        {
            eprintln!("could not publish failure report: {error}");
        }

        self.publish_final(&outcome, executor.as_ref(), &context, || {
            drop(stop_heartbeat);
            let _ = heartbeat.join();
        })
    }
}

// std-only effective-uid probe: /proc/self is owned by the process euid.
fn running_as_root() -> bool {
    fs::metadata("/proc/self")
        .map(|metadata| metadata.uid() == 0)
        .unwrap_or(false)
}

fn env_path(name: &str) -> Result<PathBuf> {
    env::var_os(name)
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
        .ok_or_else(|| format!("required environment variable {name} is missing"))
}

fn env_path_or(name: &str, fallback: &str) -> PathBuf {
    env::var_os(name)
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(fallback))
}

fn main() {
    let result = Config::from_env().and_then(|config| Supervisor { config }.run());
    if let Err(error) = result {
        eprintln!("fleet-guest-supervisor: {error}");
        std::process::exit(1);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_dir(tag: &str) -> PathBuf {
        static NEXT: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
        let serial = NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let root = env::temp_dir().join(format!(
            "fleet-guest-supervisor-test-{}-{tag}-{serial}",
            std::process::id()
        ));
        fs::create_dir_all(&root).expect("create test directory");
        root
    }

    fn have(binary: &str) -> bool {
        Command::new(binary)
            .arg("--version")
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status()
            .is_ok()
    }

    // ---- canonical metadata parsing --------------------------------------

    #[test]
    fn parses_canonical_task_meta() {
        let meta = parse_task_meta("agent=claude\nmodel=sonnet\neffort=high\n")
            .expect("valid meta");
        assert_eq!(
            meta,
            TaskMeta {
                agent: "claude".into(),
                model: "sonnet".into(),
                effort: "high".into(),
            }
        );
    }

    #[test]
    fn rejects_hostile_task_meta() {
        // Shell metacharacters — the Bash supervisor used to `source` this.
        assert!(parse_task_meta("agent=claude$(reboot)\nmodel=x\neffort=\n").is_err());
        assert!(parse_task_meta("agent=claude; rm -rf /\nmodel=x\neffort=\n").is_err());
        // Unknown keys (the retired loop-era `kind` included), duplicates,
        // malformed lines, oversized values.
        assert!(parse_task_meta("agent=claude\nPATH=/tmp\nmodel=x\neffort=\n").is_err());
        assert!(parse_task_meta("agent=claude\nmodel=x\neffort=\nkind=loop-implement\n").is_err());
        assert!(parse_task_meta("agent=claude\nagent=codex\nmodel=x\neffort=\n").is_err());
        assert!(parse_task_meta("just a line\n").is_err());
        assert!(
            parse_task_meta(&format!("agent={}\nmodel=x\neffort=\n", "a".repeat(65))).is_err()
        );
        // Missing fields parse as empty (downstream selection rejects them).
        let sparse = parse_task_meta("agent=claude\n").expect("sparse meta");
        assert_eq!(sparse.model, "");
    }

    // ---- executor and credential selection matrix ------------------------

    #[test]
    fn selects_executors_by_agent_and_model() {
        let cases = [
            (
                "claude",
                "sonnet",
                Some(("agent-claude", ExecutorKind::Claude)),
            ),
            ("codex", "gpt-5", Some(("agent-codex", ExecutorKind::Codex))),
            (
                "opencode",
                "openrouter/moonshotai/kimi-k2",
                Some(("agent-opencode", ExecutorKind::Opencode)),
            ),
            (
                "opencode",
                "local/qwen",
                Some(("agent-local", ExecutorKind::Local)),
            ),
            ("opencode", "mystery/model", None),
            ("opencode", "", None),
            // The loop-era deterministic verifier is retired.
            ("verify", "fixed", None),
            ("", "", None),
            ("surprise", "sonnet", None),
        ];
        for (agent, model, expected) in cases {
            let selected = select_executor(agent, model).map(|e| (e.user, e.kind));
            assert_eq!(selected, expected, "agent={agent} model={model}");
        }
    }

    #[test]
    fn credential_rule_matrix() {
        assert_eq!(
            credential_rule("claude", "sonnet"),
            CredentialRule::Exactly("claude-token")
        );
        assert_eq!(
            credential_rule("codex", "gpt-5"),
            CredentialRule::Exactly("codex-auth.json")
        );
        assert_eq!(
            credential_rule("opencode", "openrouter/x/y"),
            CredentialRule::Exactly("openrouter-key")
        );
        assert_eq!(credential_rule("opencode", "local/x"), CredentialRule::None);
        assert_eq!(credential_rule("verify", "fixed"), CredentialRule::Invalid);
        assert_eq!(
            credential_rule("opencode", "other"),
            CredentialRule::Invalid
        );
        assert_eq!(credential_rule("", ""), CredentialRule::Invalid);
    }

    #[test]
    fn credential_count_and_name_must_match_exactly() {
        let entry = |name: &str, regular| CredentialEntry {
            name: name.into(),
            regular,
        };
        let exactly = CredentialRule::Exactly("claude-token");
        assert!(credentials_match(&[entry("claude-token", true)], exactly));
        // Wrong name, wrong count, extra file, symlink, none at all.
        assert!(!credentials_match(
            &[entry("codex-auth.json", true)],
            exactly
        ));
        assert!(!credentials_match(&[], exactly));
        assert!(!credentials_match(
            &[entry("claude-token", true), entry("openrouter-key", true)],
            exactly
        ));
        assert!(!credentials_match(&[entry("claude-token", false)], exactly));

        assert!(credentials_match(&[], CredentialRule::None));
        assert!(!credentials_match(
            &[entry("claude-token", true)],
            CredentialRule::None
        ));
        assert!(!credentials_match(&[], CredentialRule::Invalid));
        assert!(!credentials_match(
            &[entry("claude-token", true)],
            CredentialRule::Invalid
        ));
    }

    #[test]
    fn credential_share_symlinks_are_rejected() {
        let root = temp_dir("creds");
        fs::write(root.join("real"), b"x").expect("write fixture");
        std::os::unix::fs::symlink(root.join("real"), root.join("claude-token"))
            .expect("create symlink");
        let supervisor = Supervisor {
            config: test_config(&root),
        };
        let entries = supervisor.credential_entries();
        assert!(
            entries
                .iter()
                .any(|entry| entry.name == "claude-token" && !entry.regular)
        );
        assert!(!credentials_match(
            &entries,
            CredentialRule::Exactly("claude-token")
        ));
        let _ = fs::remove_dir_all(&root);
    }

    // ---- prompt front-matter ---------------------------------------------

    #[test]
    fn strips_front_matter_like_awk() {
        assert_eq!(
            strip_front_matter("---\nagent: claude\n---\nbody\nmore\n"),
            "body\nmore\n"
        );
        // No front-matter: everything is body.
        assert_eq!(
            strip_front_matter("body\n---\nnot a header\n"),
            "body\n---\nnot a header\n"
        );
        // Unterminated header swallows the whole prompt (awk h stays set).
        assert_eq!(strip_front_matter("---\nagent: claude\nbody\n"), "");
        assert_eq!(strip_front_matter(""), "");
        // A later "---" only closes, never reopens.
        assert_eq!(strip_front_matter("---\n---\n---\nrest\n"), "---\nrest\n");
    }

    #[test]
    fn shell_quoting_is_single_quote_safe() {
        assert_eq!(shell_quote("plain-token"), "'plain-token'");
        assert_eq!(shell_quote("a'b"), "'a'\\''b'");
        assert_eq!(shell_quote("$(reboot)"), "'$(reboot)'");
        assert_eq!(trim_trailing_newlines("tok\n\n"), "tok");
        assert_eq!(trim_trailing_newlines("tok"), "tok");
    }

    // ---- publication ordering and state decisions ------------------------

    #[test]
    fn publication_order_is_lock_then_trusted_then_exit_code() {
        let steps = final_steps(true, true, true);
        let position = |step: FinalStep| {
            steps
                .iter()
                .position(|candidate| *candidate == step)
                .expect("step present")
        };
        assert_eq!(steps.last(), Some(&FinalStep::PublishExitCode));
        assert!(position(FinalStep::CapturePatch) < position(FinalStep::LockExchange));
        assert!(position(FinalStep::LockExchange) < position(FinalStep::KillExecutor));
        assert!(position(FinalStep::KillExecutor) < position(FinalStep::ResetTrusted));
        assert!(position(FinalStep::ResetTrusted) < position(FinalStep::PublishUsage));
    }

    #[test]
    fn patch_capture_requires_user_baseline_and_git() {
        for (user, baseline, git) in [
            (false, true, true),
            (true, false, true),
            (true, true, false),
        ] {
            assert!(!final_steps(user, baseline, git).contains(&FinalStep::CapturePatch));
        }
        // Without a selected user there is nothing to kill and no usage.
        let rejected = final_steps(false, false, false);
        assert_eq!(
            rejected,
            vec![
                FinalStep::LockExchange,
                FinalStep::ResetTrusted,
                FinalStep::PublishExitCode
            ]
        );
    }

    #[test]
    fn outcome_exit_codes_match_the_protocol() {
        assert_eq!(Outcome::CredentialRejected.exit_code(), 66);
        assert_eq!(Outcome::ContextFailed("log".into()).exit_code(), 65);
        assert_eq!(Outcome::MetaRejected.exit_code(), 64);
        assert_eq!(Outcome::InternalFailed("error".into()).exit_code(), 70);
        assert_eq!(Outcome::Ran(0).exit_code(), 0);
        assert_eq!(Outcome::Ran(3).exit_code(), 3);
        assert!(
            Outcome::CredentialRejected
                .message()
                .expect("message")
                .contains("credential set does not match")
        );
        assert!(Outcome::Ran(0).message().is_none());
    }

    #[test]
    fn lock_exchange_denies_group_writes() {
        let root = temp_dir("lock");
        let task_dir = root.join("task");
        fs::create_dir_all(&task_dir).expect("create task dir");
        set_mode(&task_dir, 0o770).expect("open mode");
        let supervisor = Supervisor {
            config: test_config_with_task(&root, &task_dir),
        };
        supervisor.lock_exchange().expect("lockdown");
        let mode = fs::metadata(&task_dir).expect("stat").permissions().mode();
        assert_eq!(mode & 0o7777, 0o750);
        let _ = fs::remove_dir_all(&root);
    }

    // ---- symlink and hostile-input rejection ------------------------------

    #[test]
    fn bounded_reads_refuse_symlinks_and_oversize() {
        let root = temp_dir("bounds");
        let real = root.join("real");
        fs::write(&real, b"agent=claude\n").expect("write fixture");
        let link = root.join("task-meta");
        std::os::unix::fs::symlink(&real, &link).expect("create symlink");
        assert!(read_bounded(&link, META_MAX_BYTES).is_err());
        assert!(!is_regular_nofollow(&link));
        let big = root.join("big");
        fs::write(&big, vec![b'x'; 32]).expect("write fixture");
        assert!(read_bounded(&big, 16).is_err());
        assert!(read_bounded(&big, 32).is_ok());
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn touch_refuses_symlinks() {
        let root = temp_dir("touch");
        let target = root.join("target");
        fs::write(&target, b"unchanged").expect("write fixture");
        let link = root.join("heartbeat");
        std::os::unix::fs::symlink(&target, &link).expect("create symlink");
        assert!(touch(&link).is_err());
        assert_eq!(fs::read(&target).expect("read target"), b"unchanged");
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn matching_files_skips_symlinks_and_sorts() {
        let root = temp_dir("match");
        fs::write(root.join("b.patch"), b"b").expect("write fixture");
        fs::write(root.join("a.patch"), b"a").expect("write fixture");
        fs::write(root.join("other.txt"), b"x").expect("write fixture");
        std::os::unix::fs::symlink(root.join("a.patch"), root.join("c.patch"))
            .expect("create symlink");
        let found = matching_files(&root, |name| name.ends_with(".patch"));
        let names: Vec<_> = found
            .iter()
            .map(|path| path.file_name().unwrap().to_str().unwrap().to_string())
            .collect();
        assert_eq!(names, vec!["a.patch", "b.patch"]);
        let _ = fs::remove_dir_all(&root);
    }

    // ---- trusted usage normalization fixtures ----------------------------

    #[test]
    fn claude_usage_normalization_fixture() {
        if !have("jq") {
            eprintln!("skipping: jq unavailable");
            return;
        }
        let home = temp_dir("claude-home");
        let projects = home.join(".claude/projects/demo");
        fs::create_dir_all(&projects).expect("create projects");
        fs::write(
            projects.join("session.jsonl"),
            concat!(
                r#"{"type":"user","message":{}}"#,
                "\n",
                r#"{"type":"assistant","requestId":"r1","message":{"id":"m1","model":"claude-sonnet-4-5","usage":{"input_tokens":10,"output_tokens":20,"cache_read_input_tokens":30,"cache_creation_input_tokens":40}}}"#,
                "\n",
                // Duplicate request/message id must count once.
                r#"{"type":"assistant","requestId":"r1","message":{"id":"m1","model":"claude-sonnet-4-5","usage":{"input_tokens":10,"output_tokens":20,"cache_read_input_tokens":30,"cache_creation_input_tokens":40}}}"#,
                "\n",
                r#"{"type":"assistant","requestId":"r2","message":{"id":"m2","model":"claude-opus-4-1","usage":{"input_tokens":1,"output_tokens":2}}}"#,
                "\n",
            ),
        )
        .expect("write transcript");
        let usage = claude_usage(&home, None).expect("usage extracted");
        assert_eq!(
            usage,
            r#"{"executor":"claude","model":"claude-opus-4-1","input_tokens":11,"output_tokens":22,"cache_read_tokens":30,"cache_creation_tokens":40}"#
        );
        // Empty store: no usage record at all.
        let empty = temp_dir("claude-empty");
        assert!(claude_usage(&empty, None).is_none());
        let _ = fs::remove_dir_all(&home);
        let _ = fs::remove_dir_all(&empty);
    }

    #[test]
    fn codex_usage_normalization_fixture() {
        if !have("jq") {
            eprintln!("skipping: jq unavailable");
            return;
        }
        let home = temp_dir("codex-home");
        let sessions = home.join(".codex/sessions/2026");
        fs::create_dir_all(&sessions).expect("create sessions");
        // Cumulative per-file counters: only each file's LAST value counts.
        fs::write(
            sessions.join("one.jsonl"),
            concat!(
                r#"{"type":"turn_context","payload":{"model":"gpt-5"}}"#,
                "\n",
                r#"{"type":"event_msg","payload":{"type":"token_count","info":{"total_token_usage":{"input_tokens":5,"cached_input_tokens":1,"output_tokens":2}}}}"#,
                "\n",
                r#"{"type":"event_msg","payload":{"type":"token_count","info":{"total_token_usage":{"input_tokens":100,"cached_input_tokens":40,"output_tokens":9}}}}"#,
                "\n",
            ),
        )
        .expect("write session");
        fs::write(
            sessions.join("two.jsonl"),
            concat!(
                r#"{"type":"event_msg","payload":{"type":"token_count","info":{"total_token_usage":{"input_tokens":10,"cached_input_tokens":10,"output_tokens":1}}}}"#,
                "\n",
            ),
        )
        .expect("write session");
        let usage = codex_usage(&home, None).expect("usage extracted");
        // input = (100+10) - (40+10) cached, normalized to Anthropic style.
        assert_eq!(
            usage,
            r#"{"executor":"codex","model":"gpt-5","input_tokens":60,"output_tokens":10,"cache_read_tokens":50,"cache_creation_tokens":0}"#
        );
        let _ = fs::remove_dir_all(&home);
    }

    #[test]
    fn opencode_usage_normalization_fixture() {
        if !have("jq") || !have("sqlite3") {
            eprintln!("skipping: jq or sqlite3 unavailable");
            return;
        }
        let home = temp_dir("opencode-home");
        let store = home.join(".local/share/opencode");
        fs::create_dir_all(&store).expect("create store");
        let database = store.join("opencode.db");
        let row = r#"{"role":"assistant","providerID":"openrouter","modelID":"moonshotai/kimi-k2","tokens":{"input":7,"output":11,"reasoning":13,"cache":{"read":17,"write":19}}}"#;
        let ignored = r#"{"role":"user"}"#;
        let script = format!(
            "create table message (data text);\ninsert into message values ('{row}');\ninsert into message values ('{ignored}');\n"
        );
        let mut sqlite = Command::new("sqlite3")
            .arg(&database)
            .stdin(Stdio::piped())
            .stdout(Stdio::null())
            .spawn()
            .expect("run sqlite3");
        sqlite
            .stdin
            .take()
            .expect("sqlite stdin")
            .write_all(script.as_bytes())
            .expect("feed sqlite3");
        assert!(sqlite.wait().expect("sqlite3 exit").success());
        let usage = opencode_usage(&home, None).expect("usage extracted");
        assert_eq!(
            usage,
            r#"{"executor":"opencode","model":"openrouter/moonshotai/kimi-k2","input_tokens":7,"output_tokens":24,"cache_read_tokens":17,"cache_creation_tokens":19}"#
        );
        let _ = fs::remove_dir_all(&home);
    }

    // ---- final publication on disk ---------------------------------------

    #[test]
    fn exit_code_is_published_last_and_trusted_is_root_reset() {
        let root = temp_dir("publish");
        let task_dir = root.join("task");
        fs::create_dir_all(task_dir.join(".trusted")).expect("create dirs");
        fs::write(task_dir.join(".trusted/usage.json"), b"stale").expect("plant stale usage");
        let supervisor = Supervisor {
            config: test_config_with_task(&root, &task_dir),
        };
        supervisor
            .publish_final(
                &Outcome::CredentialRejected,
                None,
                &ContextInfo::default(),
                || {},
            )
            .expect("publish");
        assert_eq!(
            fs::read_to_string(task_dir.join("exit-code")).expect("exit-code"),
            "66\n"
        );
        // The stale executor-planted record is gone and nothing replaced it.
        assert!(!task_dir.join(".trusted/usage.json").exists());
        let trusted_mode = fs::metadata(task_dir.join(".trusted"))
            .expect("trusted dir")
            .permissions()
            .mode();
        assert_eq!(trusted_mode & 0o7777, 0o700);
        let exchange_mode = fs::metadata(&task_dir)
            .expect("task dir")
            .permissions()
            .mode();
        assert_eq!(exchange_mode & 0o7777, 0o750);
        let _ = fs::remove_dir_all(&root);
    }

    // ---- helpers ----------------------------------------------------------

    fn test_config(root: &Path) -> Config {
        test_config_with_task(root, &root.join("task"))
    }

    fn test_config_with_task(root: &Path, task_dir: &Path) -> Config {
        Config {
            task_dir: task_dir.to_path_buf(),
            creds_dir: root.to_path_buf(),
            workspace: root.join("workspace"),
            context_root: root.join("context"),
            hint_file: root.join("hint.md"),
            exec_claude: root.join("bin/claude"),
            exec_codex: root.join("bin/codex"),
            exec_opencode: root.join("bin/opencode"),
            exec_local: root.join("bin/local"),
        }
    }
}
